#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# the path to the interpreter and all of the originally intended arguments
args=("$@")

# the extra options we want to pass to the interpreter
# extra_args=("--prof" "--require" "./otel-layer/instrumentation.js")
extra_args=("--require" "./otel-layer/instrumentation.js")
# extra_args=("--require" "./otel-layer/dist/instrumentation.js")
#extra_args=()
echo $date
# insert the extra options
args=("${args[@]:0:$#-1}" "${extra_args[@]}" "${args[@]: -1}")
echo "Hello from the entrypoint script with args: ${args[@]}"
# start the runtime with the extra options
exec "${args[@]}"